title: Linux For Pirates!
description: A book I'm writing about Linux
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
url: https://loftwah.github.io/linux-for-pirates

aux_links:
  Loftwah LinkFree: https://linkfree.eddiehub.io/loftwah
