name: Create issue

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-or-update-issue@v2
        with:
          issue-template: .github/ISSUE_TEMPLATE.md
          labels: bug
          title: 'Argh! A new issue matey'
