name: Generate PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Convert Markdown to PDF
      uses: pandoc/action-pandoc@v2
      with:
        inputs: index.md
        outputs: linux-for-pirates.pdf
        args: --pdf-engine=xelatex
