name: Generate PDF
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install pandoc and xelatex
      run: |
        sudo apt-get install pandoc -y
        sudo apt-get install texlive-xetex -y

    - name: Convert Markdown to PDF
      run: pandoc index.md -o linux-for-pirates.pdf --pdf-engine=xelatex

    - name: Upload PDF to main branch
      uses: actions/upload-artifact@v2
      with:
        name: linux-for-pirates.pdf
        path: linux-for-pirates.pdf
