name: Create pull request

on:
  pull_request:
    types: [opened]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-or-update-pull-request@v2
        with:
          pull-request-template: .github/PULL_REQUEST_TEMPLATE.md
          title: 'Argh! A new pull request matey'
